name: Go

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Windows
      run: GOOS=windows GOARCH=amd64 go build -o windows ec2c
    - name: Build darwin
      run: GOOS=darwin GOARCH=amd64 go build -o darwinamd ec2c
    - name: Build darwin
      run: GOOS=darwin GOARCH=arm64 go build -o darwinarm ec2c
    - name: Build darwin
      run: GOOS=linux GOARCH=amd64 go build -o linuxamd ec2c
    

    
