name: Go

on:
  push:
    branches: [ "main" ]
  

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build Windows
      uses: thatisuday/go-cross-build@v1
      with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: ''
            name: 'ec2c'
            compress: 'false'
            dest: 'binaries'
    

    
